name: CI

on: 
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github src
        continue-on-error: true
      - name: Type check with Mypy
        run: |
          pip install mypy
          make typecheck
        continue-on-error: true
      - name: Test with pytest
        run: |
          pip install pytest
          make test

